name: preload
description: >-
  Automatically generate preload tags for your Dart web application.
version: 2.0.0
homepage: https://github.com/kevmoo/preload

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: '>=0.3.0 <5.0.0'
  glob: ^2.0.0
  path: ^1.0.0

dev_dependencies:
  build_test: ^2.0.0
  logging: ^1.0.0
  pedantic: ^1.4.0
  test: ^1.2.0
